config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :categories

  map.resources :slideshows

  map.resources :slides

  map.resources :photos

  

  map.root :controller => "photos"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :photos
  acts_as_tree
    
  def ancestors_name
    if parent
      parent.ancestors_name + parent.name + ":"
    else
      ""
    end
  end
  
  def long_name
    ancestors_name + name
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :slides
  has_and_belongs_to_many :categories
  
  validates_presence_of :filename
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :slideshow
  belongs_to :photo
  
  acts_as_list :scope => "slideshow_id"
end

app/models/slideshow.rb
class Slideshow < ActiveRecord::Base
  has_many :slides, :order => :position
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @all_categories = Category.find(:all, :order => 'name')
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new
    @all_categories = Category.find(:all, :order => 'name')
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @all_categories = Category.find(:all, :order => 'name')
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to(@category)
    else
      render :action => "new"
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      flash[:notice] = 'Category was successfully updated.'
      redirect_to(@category)
    else
      render :action => "edit"
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to(categories_url)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new
    @all_categories = Category.find(:all, :order => 'name')
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
    @all_categories = Category.find(:all, :order => 'name')
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])

    if @photo.save
      flash[:notice] = 'Photo was successfully created.'
      redirect_to(@photo)
    else
      render :action => "new"
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    if @photo.update_attributes(params[:photo])
      flash[:notice] = 'Photo was successfully updated.'
      redirect_to(@photo)
    else
      render :action => "edit"
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to(photos_url)
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  # GET /slides
  # GET /slides.xml
  def index
    @slides = Slide.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @slides }
    end
  end

  # GET /slides/1
  # GET /slides/1.xml
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.xml
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.xml
  def create
    @slide = Slide.new(params[:slide])

    respond_to do |format|
      if @slide.save
        flash[:notice] = 'Slide was successfully created.'
        format.html { redirect_to(@slide) }
        format.xml  { render :xml => @slide, :status => :created, :location => @slide }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.xml
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        flash[:notice] = 'Slide was successfully updated.'
        format.html { redirect_to(@slide) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.xml
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to(slides_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController
  # GET /slideshows
  # GET /slideshows.xml
  def index
    @slideshows = Slideshow.all
  end

  # GET /slideshows/1
  # GET /slideshows/1.xml
  def show
    @slideshow = Slideshow.find(params[:id])
  end

  # GET /slideshows/new
  # GET /slideshows/new.xml
  def new
    @slideshow = Slideshow.new
  end

  # GET /slideshows/1/edit
  def edit
    @slideshow = Slideshow.find(params[:id])
  end

  # POST /slideshows
  # POST /slideshows.xml
  def create
    @slideshow = Slideshow.new(params[:slideshow])

    if @slideshow.save
      flash[:notice] = 'Slideshow was successfully created.'
      redirect_to(@slideshow)
    else
      render :action => "new"
    end
  end

  # PUT /slideshows/1
  # PUT /slideshows/1.xml
  def update
    @slideshow = Slideshow.find(params[:id])

    if @slideshow.update_attributes(params[:slideshow])
      flash[:notice] = 'Slideshow was successfully updated.'
      redirect_to(@slideshow)
    else
      render :action => "edit"
    end
  end

  # DELETE /slideshows/1
  # DELETE /slideshows/1.xml
  def destroy
    @slideshow = Slideshow.find(params[:id])
    @slideshow.destroy

    redirect_to(slideshows_url)
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
  
  def thumbnail_tag(slide)
    image_tag "photos/#{slide.photo.thumbnail}" if slide
  end
end

app/views/categories/_form.html.erb
<%= f.error_messages %>

<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :parent_id %>
  <%= f.collection_select :parent_id, @all_categories, :id, :long_name %>
</p>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<% form_for(@category) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @all_categories.each do |category| %>
  <tr>
    <td><%=h category.long_name %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<% form_for(@category) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <b>Parent:</b>
  <%=h @category.parent_id %>
</p>

<p>
  <b>Name:</b>
  <%=h @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" /> 
  <title>Photos: <%= controller.action_name %></title> 
  <%= stylesheet_link_tag 'application', 'photos', 'slideshows' %> 
</head> 
<body> 
    
<div style="background-color:LightBlue"> 
    <p class="navbar"> 
      &nbsp; 
      <%= link_to 'Photos', photos_path %> 
      &nbsp; 
      <%= link_to 'Categories', categories_path %> 
      &nbsp; 
      <%= link_to 'Slideshows', slideshows_path %> 
    </p> 
</div>
 
<p style="color: green"><%= flash[:notice] %></p> 

<%= yield  %> 

</body> 
</html>

app/views/photos/_form.html.erb
<%= f.error_messages %>

<p>
  <%= f.label :filename %><br />
  <%= f.text_field :filename %>
</p>
<p>
  <%= f.label :thumbnail %><br />
  <%= f.text_field :thumbnail %>
</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :categories %><br />
  <%= f.collection_select :category_ids, @all_categories, :id, :long_name, {}, { :multiple => true } %>
</p>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<% form_for(@photo) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
<% @photos.each do |photo| %>
  <tr>
    <td><%= link_to(image_tag("photos/#{photo.thumbnail}", :id => "thumbnail", :size => "75x56", :border => 1), photo) %></td>
    <td><%=h photo.filename %></td>
    <td><%= link_to 'delete me', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<% form_for(@photo) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<%= image_tag 'photos/' + @photo.filename %>

<p>
  <b>Filename:</b>
  <%=h @photo.filename %>
</p>

<p>
  <b>Thumbnail:</b>
  <%=h @photo.thumbnail %>
</p>

<p>
  <b>Description:</b>
  <%=h @photo.description %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<% form_for(@slide) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </p>
  <p>
    <%= f.label :photo_id %><br />
    <%= f.text_field :photo_id %>
  </p>
  <p>
    <%= f.label :slideshow_id %><br />
    <%= f.text_field :slideshow_id %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <tr>
    <th>Position</th>
    <th>Photo</th>
    <th>Slideshow</th>
  </tr>

<% @slides.each do |slide| %>
  <tr>
    <td><%=h slide.position %></td>
    <td><%=h slide.photo_id %></td>
    <td><%=h slide.slideshow_id %></td>
    <td><%= link_to 'Show', slide %></td>
    <td><%= link_to 'Edit', edit_slide_path(slide) %></td>
    <td><%= link_to 'Destroy', slide, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<% form_for(@slide) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </p>
  <p>
    <%= f.label :photo_id %><br />
    <%= f.text_field :photo_id %>
  </p>
  <p>
    <%= f.label :slideshow_id %><br />
    <%= f.text_field :slideshow_id %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p>
  <b>Position:</b>
  <%=h @slide.position %>
</p>

<p>
  <b>Photo:</b>
  <%=h @slide.photo_id %>
</p>

<p>
  <b>Slideshow:</b>
  <%=h @slide.slideshow_id %>
</p>


<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>

app/views/slideshows/edit.html.erb
<h1>Editing slideshow</h1>

<% form_for(@slideshow) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @slideshow %> |
<%= link_to 'Back', slideshows_path %>

app/views/slideshows/index.html.erb
<p><%= link_to 'New slideshow', new_slideshow_path %></p>

<div id="slideshow-summaries">
<% @slideshows.each do |slideshow| %>
  <div class="slideshow-summary">
    <div class="slideshow-caption">
      <%= slideshow.name %></td>
      <small>(<%= slideshow.slides.size %> slides)</small>
    </div>
    
    <div class="slideshow-thumbnails">
      <% 5.times do |i| -%>
        <%= thumbnail_tag slideshow.slides[i] %>
      <% end -%>    
      &nbsp;<strong>...</strong>
    </div>
    
    <div class="slideshow-controls">
      <%= link_to 'Play', slideshow %>
      <%= link_to 'Edit', edit_slideshow_path(slideshow) %>
      <%= link_to 'Delete', slideshow, :confirm => 'Are you sure?', :method => :delete %>
    </div>
  </div>
<% end %>
</div>

<br />

app/views/slideshows/new.html.erb
<h1>New slideshow</h1>

<% form_for(@slideshow) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', slideshows_path %>

app/views/slideshows/show.html.erb
<p>
  <b>Name:</b>
  <%=h @slideshow.name %>
</p>


<%= link_to 'Edit', edit_slideshow_path(@slideshow) %> |
<%= link_to 'Back', slideshows_path %>